### ISSUE TITLE
Testing the Android SDK for Piwik

### ISSUE THREAD

**Issue by mattab** [piwik/piwik-sdk-android#1]
The goal of this project is to build a SDK for Android to measure your apps with Piwik. We have started implementing the SDK. We are now looking for help from the community to review and test our Android SDK!

If you are:
 * familiar with SDK app development
 * familiar with Java 
 * and you can spare a bit of time to help us review the SDK and test it on your Android App

please leave a comment in this issue. 

With your help we can make the official Android SDK for Piwik a success :+1:  Thank you!

(we will notify you here as soon as the SDK is ready to be reviewed and tested!)

**Comment by d4rken** [comment]
@mattab this could also be closed so people create new issues for any more changes or concerns they have.

**Comment by mattab** [comment]
sounds good, the SDK has been publicly released so this issue can be closed. Well done @dotsbb and now also you @d4rken :)
