### ISSUE TITLE
Can't compile with version 1.0.0

### ISSUE THREAD

**Issue by itshnegg** [piwik/piwik-sdk-android#105]
The following error occurs when I add 'compile 'org.piwik.sdk:piwik-sdk:1.0.0' to the dependencies.

Error:Failed to resolve: com.jakewharton.timber:timber:4.1.3-20160408.041006-2

**Comment by d4rken** [comment]
Thanks for the report, I'm looking into it. Will likely be fixed by #106

**Comment by d4rken** [comment]
Should be resolved.
