### ISSUE TITLE
0% coverage

### ISSUE THREAD

**Issue by d4rken** [piwik/piwik-sdk-android#109]
Why does the coverage show 0%?

https://coveralls.io/github/piwik/piwik-sdk-android?branch=master

**Comment by dotsbb** [comment]
Very strange, I'll try to fix it ASAP

**Comment by d4rken** [comment]
What caused it?

**Comment by dotsbb** [comment]
@d4rken new version of JaCoCo plugin which came with gradle update here https://github.com/piwik/piwik-sdk-android/pull/100/files#diff-c197962302397baf3a4cc36463dce5eaR8

**Comment by d4rken** [comment]
Do you know why that new version break coverage reporting?

**Comment by dotsbb** [comment]
Don't know, but this workaround is placed under "Potential breaking changes" section here https://docs.gradle.org/current/release-notes#jacoco-version-upgrade-to-0.7.6
