### ISSUE TITLE
Documentation to install and use the Android SDK for Piwik in your app 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik-sdk-android#11]
The goal of this issue is to provide users of the SDK a useful Readme file and documentation.

Here is some inspiration for the guide: 
 * Here are good example of SDK Android documents: [Piwik iOS SDK](https://github.com/piwik/piwik-sdk-ios), Google Analytics [Android SDK intro](https://developers.google.com/analytics/devguides/collection/android/v4/), [Countly SDK Android](https://github.com/countly/countly-sdk-android) 
 * Some parts of the [Design document](https://github.com/piwik/piwik-sdk-android/wiki/Design-document) maybe are useful and can be reused.

The documentation can be put in the Readme.md file so it is accessible at first page load for all users. Having an easy to read guide will greatly help the adoption of our SDK, and make Android developers happy!

This is the last step before we can publicly announce the SDK to the community https://github.com/piwik/piwik/issues/4733

**Comment by d4rken** [comment]
I think this can be closed @mattab.
