### ISSUE TITLE
Failed to resolve: org.piwik.sdk:piwik-sdk:1.0.1

### ISSUE THREAD

**Issue by thkus** [piwik/piwik-sdk-android#112]
Hi, i included the dependency as stated in the Documentation. However gradle seems unable to resolve the dependency. I found https://github.com/piwik/piwik-sdk-android/issues/67 which seems to be a similar Issue.

Any Idea on how to resolve this?

**Comment by d4rken** [comment]
In contrast to #67, the files for 1.0.1 are there though:
https://jcenter.bintray.com/org/piwik/sdk/piwik-sdk/1.0.1/
https://bintray.com/darken/maven/piwik-sdk-android/1.0.1/view#files/org/piwik/sdk/piwik-sdk/1.0.1

Did you include `jcenter()` as repository?

**Comment by thkus** [comment]
Yes, that was the problem. `jcenter()` was not included as repository. Thank you!
