### ISSUE TITLE
Unable to connect local piwik

### ISSUE THREAD

**Issue by MostafaDavodi** [piwik/piwik-sdk-android#116]
i implement default method of demo application in my android app and use TrackHelper for sending request to local piwik , but when i see network logs i can't see my request despite when use getTracker().getAPIUrl().toString() see the correct path . 

here is my sample code : 

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        CalligraphyConfig.initDefault(new CalligraphyConfig.Builder()
                .setDefaultFontPath("fonts/IRANSansMobile_Bold.ttf")
                .setFontAttrId(R.attr.fontPath)
                .build()
        );

        TrackHelper.track().screen("/").title("First Activity").with(getTracker());

        Toast.makeText(MainActivity.this, getTracker().getAPIUrl().toString() , Toast.LENGTH_SHORT).show();

        TextView tv = (TextView)findViewById(R.id.first);
        tv.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent = new Intent(MainActivity.this, SecondActivity.class);
                startActivity(intent);
            }
        });

    }

    private Tracker getTracker() {
        return ((PiwikApplication) getApplication()).getTracker();
    }

**Comment by d4rken** [comment]
If you `Timber.plant(new Timber.DebugTree());` you should see piwik logging output in logcat.

Make sure you are not in dryrun mode and note that default dispatch interval is 120s.

**Comment by MostafaDavodi** [comment]
good, thank you :)

**Comment by d4rken** [comment]
So it works now?

**Comment by MostafaDavodi** [comment]
yes, it works properly . thank you
