### ISSUE TITLE
Why is minSDK to API 10 and not API 9 ?

### ISSUE THREAD

**Issue by eldk** [piwik/piwik-sdk-android#122]
Hello,

Why minSDK is to API 10 and not API 9 ?

https://github.com/piwik/piwik-sdk-android/blob/8cbc3aa41c7de82ba65ce14baefaeb043f7bd4e4/piwik-sdk/build.gradle

https://developer.android.com/about/versions/android-2.3.3.html

https://developer.android.com/sdk/api_diff/10/changes.html

Thanks,

Eric

**Comment by d4rken** [comment]
API9 was completely replaced by API10, meaning, all devices that got the API9 update, also got the API10 update. There is no noticeable amount of devices still running on API9.

To keep Android code headache free a minSdk should be choosen by "go as low as you need", not by "go as low as you can".

**Comment by eldk** [comment]
Ok,
as I have some users with API 9 reported, I will downgrade to api 9 in my piwik build .
Thanks
