### ISSUE TITLE
No tracking

### ISSUE THREAD

**Issue by nicolaiendios** [piwik/piwik-sdk-android#133]
I implemented Piwik in my app just like the sample code but it doesn't track anything. Only works on iOS. Are there any known issues with the SDK that make tracking impossible at this moment?

**Comment by eldk** [comment]
Hello,

I use it since a few weeks, no problem.

Eric

**Comment by nicolaiendios** [comment]
Hey Eric!

Thanks for the reply.
The SDK is not giving me any Logs at all. Should I be getting them automatically or do I have to turn it on?

Thanks
Nicolai

**Comment by eldk** [comment]
Hello,

Have a look here : https://github.com/piwik/piwik-sdk-android#debugging

And here :  https://github.com/piwik/piwik-sdk-android/blob/master/exampleapp/src/main/java/com/piwik/demo/DemoApp.java#L37

Without forget this : https://github.com/piwik/piwik-sdk-android/blob/master/exampleapp/src/main/java/com/piwik/demo/DemoApp.java#L16

When logs will be enable things should be clearer.

Thanks,

Eric

**Comment by nicolaiendios** [comment]
Thanks a lot Eric!

I will try it out and hopefully find my bug.

Cheers
Nicolai
