### ISSUE TITLE
Handle search events

### ISSUE THREAD

**Issue by Riedi2070** [piwik/piwik-sdk-android#134]
Dear guys,

I'm using this library to creating analytics for my android app. It's a greate project, but I'm missing some little features or I have just not found them yet.

I would like track search events. In php I can do it with the function `doTrackSiteSearch($searchValue, $searchCat, $resultCounts)` but in this Android SDK I missing this or a similar function.
Also I haven't found a function, with which I can set URL-variables manually. For search events, I could set the URL-variables `&search`, `&search_cat` and `&search_count` in the url request, but I don't know how I can fireing an custome request with this sdk.

May be somebody has the same problem and a solution for me.

Much thanks

**Comment by d4rken** [comment]
The `TrackHelper` class currently has no helper functions for site search.

You can create custom requests by creating a `TrackMe` object (from scratch or prebuild through `TrackHelper`), set/modify query paramters on it, and then submit that to the `Tracker`.
