### ISSUE TITLE
i get Value not defined in Custom Dimension

### ISSUE THREAD

**Issue by kamranr123** [piwik/piwik-sdk-android#137]
Hi

i used custom Custom Dimensions in my app. but in server for a single Custom Dimensions, i get 'Value not defined' exactly equal to all of the unrelated actions that tracked. Based on documentation for Custom Dimensions "By default a report for a Custom Dimension in scope “Action” will show values across all kinds of actions (page views, events, content tracking, downloads, etc.)"
what can I do to don't get all actions in my Custom Dimensions  section on the server?
i can do it by using Segmentation, but i want to do something in my app programmatically.

thanks

**Comment by dotsbb** [comment]
@kamranr123 probably this bug caused by plugin, not SDK itself. Please see https://github.com/piwik/plugin-CustomDimensions/issues/32.
