### ISSUE TITLE
FYI: Piwik Tracking API now allows data up to 24 hours in the past

### ISSUE THREAD

**Issue by mattab** [piwik/piwik-sdk-android#139]
Dear SDK maintainer & SDK users, 

Here is a quick notice regarding an important Tracking API improvement in Piwik 3: it is now possible to store data in the past up to 24 hours in the past. In Piwik 2, only data up to 4 hours could be stored in the past. This should hopefully help build a more useful offline tracking mechanism in #16. This core improvement was done in: https://github.com/piwik/piwik/issues/10968

As there is likely nothing to do feel free to close the issue.

If you have any question or suggestion  we're here to help :) 

Cheers!

**Comment by d4rken** [comment]
#141 and also accounted for in #136
