### ISSUE TITLE
compile source for local maven repository

### ISSUE THREAD

**Issue by croniserb** [piwik/piwik-sdk-android#140]
For our development project, I am required to gather all third party source and build them.  Then host them on an internal maven repository for CM requirements.  I have built the jar file successfully and deployed it to the maven repository.  The issue is the timber dependency of piwik.  My project is crashing at run time due to the dependency.  The project compiles without errors. I have tried to add the timber jar to my project but I have been unable to get around the issue.  compile 'org.piwik.sdk:piwik-sdk:1.0.1' does not work if I deploy the aar to the local repository.  Attached it the crash log. Thanks in advance.
[CRASH_2016_12_14_09_18_12.txt](https://github.com/piwik/piwik-sdk-android/files/652012/CRASH_2016_12_14_09_18_12.txt)

**Comment by dotsbb** [comment]
I can see error `java.lang.ClassNotFoundException: Didn't find class "timber.log.Timber"`
@croniserb could you try to add `compile 'com.jakewharton.timber:timber:4.1.2'` or similar?

**Comment by croniserb** [comment]
@dotsbb I tried https://github.com/JakeWharton/timber/releases the 4.1.2.  I have tried both the aar and the jar as I have done with piwik.  I have even tried to put them in a local libs directory instead of maven.  I still am getting the error that is attached.  It seems like the piwik dependency is not being picked up when I attempt to use it locally.  Thanks.

**Comment by d4rken** [comment]
@croniserb If this is no longer a current topic, please close it. Preferably add your solutation if you solved it.

**Comment by d4rken** [comment]
Stale.
