### ISSUE TITLE
Update guide from v1.0.2 to v2.0 of the SDK

### ISSUE THREAD

**Issue by PattaFeuFeu** [piwik/piwik-sdk-android#161]
Is there any resource that guides through the changes that occurred during the version upgrade from v1 to v2 of the SDK?
Changes like “TrackHelper can now be found under sdk.extra instead of sdk”, “Instead of ‘setOptOut’, please use XY now”, and so on?

**Comment by d4rken** [comment]
Unfortunately not.

Could write one and we'll add it to the wiki?

**Comment by PattaFeuFeu** [comment]
At the moment, I don’t have the time to write an article on that matter. But I could write down a few lines underneath this ticket with findings I obtained along the way while updating from 1.0.2 to 2.0.

**Comment by PattaFeuFeu** [comment]
# Update guide 1.0 --> 2.0

## Gradle

Update from

`compile 'org.piwik.sdk:piwik-sdk:1.0.2'`

to

`compile 'org.piwik.sdk:piwik-sdk:2.0.0'`

## Classes that moved

### TrackHelper

TrackHelper moved from `org.piwik.sdk` to `org.piwik.sdk.extra` --- the new fully qualified name therefore becomes `org.piwik.sdk.extra.TrackHelper`

## Methods that changed

### CustomVariables

> CustomVariables have been deprecated.
_See https://github.com/piwik/piwik-sdk-android/pull/148#issuecomment-277723478_

**Comment by PattaFeuFeu** [comment]
What happened to `setDryrun(boolean)`? I cannot seem to find it.

**Comment by d4rken** [comment]
The dev now supplies their own list datastructure that the packets during dryrun will be placed into.

https://github.com/piwik/piwik-sdk-android/blob/master/piwik-sdk/src/main/java/org/piwik/sdk/Tracker.java#L542

https://github.com/piwik/piwik-sdk-android/blob/master/piwik-sdk/src/main/java/org/piwik/sdk/dispatcher/Dispatcher.java#L214

**Comment by PattaFeuFeu** [comment]
I updated my “wiki” comment with all changes I found when updating my codebase. Feel free to add additional pieces of information and also to add my findings to the wiki.

**Comment by d4rken** [comment]
Awesome!

https://github.com/piwik/piwik-sdk-android/wiki/Migration
