### ISSUE TITLE
not able to give Custom path while Tracking the pages

### ISSUE THREAD

**Issue by diana-doss** [piwik/piwik-sdk-android#165]
I am trying to track a screen with piwik as below 

` TrackHelper.track().screen("/global/").title("Home Screen").with(androidTracker);`

but when we see it on dashboard we are able to see the package name by default and then our path appended next to it.

Please find the screen shot below 
<img width="544" alt="screen shot 2017-05-17 at 1 37 11 pm" src="https://cloud.githubusercontent.com/assets/25843933/26144438/72aa49ce-3b06-11e7-9c88-f46a41325163.png">

Let me know if there  is a way to avoid the package name from the path

**Comment by dotsbb** [comment]
@diana-doss You could use [`setApplicationDomain`](https://github.com/piwik/piwik-sdk-android/blob/master/piwik-sdk/src/main/java/org/piwik/sdk/Tracker.java#L367-L377) method in order to customise visible domain name.
