### ISSUE TITLE
please help me to use the piwik

### ISSUE THREAD

**Issue by roorey** [piwik/piwik-sdk-android#166]
I use wampService set a Local Service. In MyApplication(extends PiwikApplication),i want to use the TrackerConfig.createDefault("url",3); but i don`t kunow the url ,please tell me about the content of url.thank you very much!

**Comment by d4rken** [comment]
The `url` is the address of your piwik server. For more details regarding Piwik server setup check here: https://piwik.org/docs/installation/

**Comment by roorey** [comment]
OK , I got it ,And succeed  Thank you .
