### ISSUE TITLE
Can I track several time my views ?

### ISSUE THREAD

**Issue by Malcom100** [piwik/piwik-sdk-android#167]
Hello,

I have a little problem but maybe it is normal. I will to try explain to you with an example:
user goes to view A -> view B -> view C : three views are tracked
when user back to view B and view A : these view are not tracked

Is it normal the view can't be tracked several time ? 

Thanks in advence for your answer

**Comment by d4rken** [comment]
Sounds like you are tracking in something like `Fragment.onCreate` which doesn't get called a second time because the existing Fragment is reused.

**Comment by Malcom100** [comment]
Alrigth I understood, so it is better to use it in onViewCreated method ! I will check it.
Thanks
