### ISSUE TITLE
Expectations have not been met

### ISSUE THREAD

**Issue by HaDiSs277** [piwik/piwik-sdk-android#175]
Hi, i read in your site about [how use piwik for tack mobile app activities](https://piwik.org/blog/2012/04/how-to-use-piwik-to-track-mobile-apps-activity-clicks-phones-errors-etc/)
How to track all of things that you said? like these
"how long users spend in the app,"
"how often is the app opened? When and how long is the app opened?"
How can i see them in panel? or how can i track them?
And my other question is that why piwik cant recognize my user city? it's always unknown

**Comment by d4rken** [comment]
> Hi, i read in your site about how use piwik for tack mobile app activities
> How to track all of things that you said? like these
> "how long users spend in the app,"
> "how often is the app opened? When and how long is the app opened?"
> How can i see them in panel? or how can i track them?

I would recommend checking out the example app: https://github.com/piwik/piwik-sdk-android/tree/master/exampleapp

> And my other question is that why piwik cant recognize my user city? it's always unknown

Possibly due to anonymized IPs or incomplete geographic data for matching the IPs.

**Comment by HaDiSs277** [comment]
At first i had made my project equal to your sample.
In pannel i dont know where shows "how long users spend in the app" and" "how offen is the app opened? when and how long is the app opened?"

**Comment by HaDiSs277** [comment]
Why you don't answer my question?

**Comment by d4rken** [comment]
> "how long users spend in the app"

This is basically the session duration.

> "how often is the app opened? when and how long is the app opened?"

This would be the visit count also session durations.

Those metrics are tracked automatically by Piwik if you do screen tracking in your app.

In the Android SDK, a session lasts as long as the `Tracker` instance exists, so normally for the duration the app is alive (e.g. in memory).

> And for anonymized IPs, it recognizes my country but cant recognize my city that i am. its very important to me.

This is done by https://github.com/piwik/piwik, not the Android SDK.

**Comment by d4rken** [comment]
> Expectations have not been met

Feel free to submit a pull request if you feel something could be improved.
