### ISSUE TITLE
Mention all available features of the SDK in the README

### ISSUE THREAD

**Issue by mattab** [piwik/piwik-sdk-android#176]
It would be great to help users discover the power of the Android SDK if all features were listed, eg. in a bullet point list, in the README. For example "Tracking of events that occurred while user was offline." and all other "basic" and any other non obvious feature. Will help get more users excited and realise the power of the project :+1:

**Comment by d4rken** [comment]
@mattab  I've updated the README with a feature list. If you think that it's sufficient, please close the ticket.

I think the github repo short description could be better too but I can't edit that.

Out of curiousity why is this repo BSD-3, Piwik GPL-3 and the iOS app MIT? Seems so chaotic.

**Comment by mattab** [comment]
Looks great @d4rken thanks for the update!

Piwik is GPL-3 (Freedom Software). But our SDKs (iOS, Android, PHP SDK, C#, Java, etc.) cannot be GPL-3 as it does not work for a library (or it would force users of the library to be under GPL as well). BSD-3 clause is the new standard for our library, almost all of them should use it already, except iOS SDK, Created an issue here to request/suggest to change the license: https://github.com/piwik/piwik-sdk-ios/issues/212

Cheers!
