### ISSUE TITLE
Why are Piwik instances tracked against a HashMap of Application objects

### ISSUE THREAD

**Issue by d4rken** [piwik/piwik-sdk-android#23]
AFAIK, the Application object is a singleton that lives as long as the app process exists. There will not be a case where we pass different application objects to Piwik.getInstance(...).

I think we could just remove the HashMap. Did I miss anything?

**Comment by dotsbb** [comment]
You totally right, there is no need of HashMap. It could be rewritten by users (if they want more than 1 tracker) to something like  this https://developers.google.com/analytics/devguides/collection/android/v4/#tracking-methods

**Comment by d4rken** [comment]
This will be resolved by #34
