### ISSUE TITLE
Chaos in autoBindActivities

### ISSUE THREAD

**Issue by d4rken** [piwik/piwik-sdk-android#24]
Currently onActivityStarted & onActivityResumed both end up calling activityStart(...), leading to 2 tracked screen views each time the activity starts (app starts / app rotation).

When onActivityPaused & onActivityStopped is called, they both call through to activityStop(...). In the same case as above we trying to dispatch two times directly after each other.
The documentation also states that stopAutoDispatching() would be called when the Activity is paused, but this is currently not happening.

I propose to change it like this:
onActivityStarted ->
onActivityResumed ->  start autodispatching & track screen view
onActivityPaused -> stop auto dispatching
onActivityStopped -> dispatch remaining events
onActivityDestroyed ->

**Comment by dotsbb** [comment]
:+1: I'd definitely merge your pull request.

**Comment by d4rken** [comment]
This is resolved, any further discussion can be done in #30.
