### ISSUE TITLE
Proposal: Remove compiled jar from repo, attach to tagged releases

### ISSUE THREAD

**Issue by d4rken** [piwik/piwik-sdk-android#31]
Currently the repo contains the compiled jar here:
https://github.com/piwik/piwik-sdk-android/tree/master/piwik_sdk/jar
It's difficult to track against which code version it was built and everytime you make a testbuild it gets changed and suggested to be recommitted by git.
Additionally it's quickly outdated and we don't want (do we?) have to build and update it with each PR.
(Currently the jar doesn't already match the latest code).

I would suggest to remove the jar from the repo and attach it to each release as download:
https://github.com/piwik/piwik-sdk-android/releases

@dotsbb or @mattab could then choose certain commits, tag it and create a new release.

**Comment by mattab** [comment]
or maybe we could build the JAR from travis so it's done automatically on each commit?

**Comment by d4rken** [comment]
If that is possible that would be cool :).
We should differentiate between some "stable" and one "bleeding edge" version though.

**Comment by mattab** [comment]
Each commit has its own build. So then when you make a release on github it will create a tags/x.y.z and a commit, which will trigger a build which could build the Android SDK.
