### ISSUE TITLE
Proposal: Switch to a master/dev branch setup

### ISSUE THREAD

**Issue by d4rken** [piwik/piwik-sdk-android#32]
Currently all changes and PR are merged into the master branch.
I suggest we create a dev branch.
All changes and PR are done on the dev branch.
At certain points someone says "time for a new release":
* Merge the dev branch into master
* Tag the last commit in master after the merge
* Create a new release for this tag, build the jar, attach it.
* Increase the version code+name in the sdk gradle file on the dev branch (i.e. new version in the making)

At this point the cycle starts from the beginning.

What do you think @dotsbb ?

TODO:
* Create new branch
* Update docs to describe this
* Possibly update travis-ci to do it's magic on the dev branch? Not sure still inexperienced with travis

**Comment by dotsbb** [comment]
Absolutely agree. I'll handle travis.

**Comment by d4rken** [comment]
Need me to do anything? Except send new PR via the dev branch.
