### ISSUE TITLE
Tag release v0.0.2

### ISSUE THREAD

**Issue by d4rken** [piwik/piwik-sdk-android#60]
@dotsbb Can you tag https://github.com/piwik/piwik-sdk-android/commit/9237099a7df67d50e78e4f3956428443274858a6 on as v0.0.2 and publish it as release under https://github.com/piwik/piwik-sdk-android/releases ?

**Comment by d4rken** [comment]
Actually,  https://github.com/piwik/piwik-sdk-android/commit/a2c8ee1e519684b10d03256ec5aa77aaa8052dac
I'll submit a PR

**Comment by d4rken** [comment]
Nevermind, you can submit tags via PR :astonished: , you'll have to do that.

**Comment by dotsbb** [comment]
Done :+1:
