### ISSUE TITLE
Version 1.0.0 ?

### ISSUE THREAD

**Issue by mattab** [piwik/piwik-sdk-android#64]
Hi @dotsbb 

When do you think we could release version 1.0.0 of the Android SDK?

What would you like to include in this 1.0.0 release?

**Comment by dotsbb** [comment]
We could release 1.0.0 version with introduced offline mode #16  and fixed deprecated classes #61 at least.
Nice thing to have is Android 6.0 support: example app and gradle settings should be updated.

**Comment by d4rken** [comment]
A 1.0.0 release usually means some kind of API commitment.
So we should be happy with the way the API looks.
Are we happy?

#61 is not much work. After that we should be able to build against API 23 (if there is no unforseen conflict, sometimes testing libs throw weird errors when building against newer APIs). I might do that on sunday with a nice cup of coffee.

#16 Is more tricky. I'll post some my ideas in the ticket though.@dotsbb would love to hear your thoughts on them.

The example app still contains a url to a piwik instance which 404s. What do we do with that?
@mattab It would be nice to have a working piwik instance for users to play around with. Maybe the demo app could post specific events to the piwik demo instance ?

**Comment by d4rken** [comment]
We will do 1.0.0 without offline support for now.

I'll do 2-3 PRs this week, then I would say we release 1.0.0 officially.
My TODO
* Some small code polish
* A few additional helper methods within the TrackHelper
* Replacing the current logging mechanism with Timber

Can you think of anything else we might want to do @dotsbb ?

Offline support can still be added transparently later. I've looked into offline support of a few other analytics SDKs and got some idea what we don't want to do, coupled with the points in #16, maybe I'll submit a draft and @dotsbb could give me some feedback on it. While I don't really miss an offline mode, for competitiveness it should exist.

**Comment by dotsbb** [comment]
@d4rken sounds like a very good plan to me. Didn't know about Timber before. I look forward to see your draft.

**Comment by d4rken** [comment]
Timber requires minApi 15 :(

**Comment by d4rken** [comment]
v1.0.0 has been merged into master, tagged and I've pushed v1.0.0 to bintray.

**Comment by d4rken** [comment]
@dotsbb If you have time, can you create a release entry for v1.0.0 on Github?

**Comment by mattab** [comment]
Awesome work on 1.0.0 release @d4rken @dotsbb :tada: 

Congratulations and a big thank you from the Piwik community!
