### ISSUE TITLE
Failed to resolve: org.piwik.sdk:piwik-sdk:0.0.3

### ISSUE THREAD

**Issue by corentindesfarges** [piwik/piwik-sdk-android#67]
Hi,

I added the sdk to my project dependences (build.gradle)
```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    ...
    compile 'org.piwik.sdk:piwik-sdk:0.0.3'
}
```
When I sync the project, I get this error :
![image](https://cloud.githubusercontent.com/assets/5452616/10576824/8d6e5d06-7666-11e5-885a-6bb197f4e2b4.png)

Am I doing something wrong?

**Comment by d4rken** [comment]
Nope, you are not.
Looks like the previous bintray/jcenter upload was faulty, sorry for that.

Should be fixed now, try again.

Previously the metadata file was not updated and javadoc/source files were missing too... weird.

https://bintray.com/darken/maven/piwik-sdk-android/0.0.3/view/general#files
https://jcenter.bintray.com/org/piwik/sdk/piwik-sdk/
