### ISSUE TITLE
piwik-sdk inside project

### ISSUE THREAD

**Issue by er1cka** [piwik/piwik-sdk-android#68]
hi guys' sorry but i am new on java development, may i ask how to include piwik-sdk inside a project not getting from github or maven? thanks in advance :)

i am using android studio for my platform.

**Comment by d4rken** [comment]
If including the library via gradle is not an option, you can also build a jar file.

```
gradlew :piwik-sdk:clean :piwik-sdk:assemble :piwik-sdk:makeJar
```
