### ISSUE TITLE
Supporting more than 5 Custom Variables

### ISSUE THREAD

**Issue by derekchan** [piwik/piwik-sdk-android#69]
It is possible to configure Piwik to receive more than 5 cvars (http://piwik.org/faq/how-to/faq_17931/). 

CustomVariables.java is currently hard-coded to support 5 CVars. Should we instead make it configurable?

```    
    private static final int MAX_VARIABLES = 5;
    protected static final int MAX_LENGTH = 200;

    public CustomVariables() {
        super(MAX_VARIABLES);
    }
```

**Comment by d4rken** [comment]
Sure, we could do that.
Are you currently obstructed by this limitation?

I would suggest we pass this as parameter within the Tracker constructor as it is something that doesn't and shouldn't change over the objects lifetime.
As the Tracker constructor parameters are becoming quite unwiedly we could introduce a TrackerConfig class. Each setter of this class should have javadoc that explains the option. Especially in case of the custom variables that this needs to be configured serverside too.

I'm not yet sure though how we could elegantly ensure that the CustomVariables object within the TrackMe class also adheres to this configuration.

**Comment by d4rken** [comment]
Limit was removed by @dotsbb in #90
