### ISSUE TITLE
Let users track Custom Dimensions 

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik-sdk-android#70]
In https://github.com/piwik/piwik/issues/9129 we created a new plugin to track Custom Dimensions.

To the JavaScript Tracker we added a new method `setCustomDimension(int dimensionId, string dimensionValue)`. This sets a tracking API parameter `dimension$dimensionId=$dimensionValue`. Eg `dimension1=foo` or `dimension2=bar`. So the tracking API parameter starts with `dimension` followed by the set `dimensionId`. 

I reckon we should be consistent here with the PHP Tracker and clear all set custom dimensions after the next tracking request was sent. 
eg
```
setCustomDimension(1, 'myvalue1')
setCustomDimension(2, 'myvalue2)
trackPageview()
// now dimension 1 and 2 would be cleared and one has to set values again
```

FYI: Custom Dimensions are similar to Custom Variables. Currently a plugin is needed to use them but in Piwik 3.0 it will be installed by default and at some point we will deprecate Custom Variables (not soon though)

**Comment by tsteur** [comment]
BTW: In PHP-Tracker we used a more generic implementation see: https://github.com/piwik/piwik-php-tracker/pull/15/files 

It's basically a method `setCustomTrackingParameter(parameter, value)` that let's you set a dimension like this: `setCustomTrackingParameter('dimension1', 'my value')`. Also in the future it will let you set any custom tracking parameter for any custom plugin.

**Comment by d4rken** [comment]
I favor the generic approach especially as the functionality is still a plugin, additionally this would be flexible for future enhancements.

We could note the planned changes for ```setCustomVariables``` (maybe @deprecate ?) in the javadocs and add the plugin as example to the javadoc for ```setCustomTrackingParameter```

For future reference: https://github.com/piwik/plugin-CustomDimensions

**Comment by dotsbb** [comment]
@tsteur @d4rken I'll do this one using generic approach.

**Comment by tsteur** [comment]
> @tsteur @d4rken I'll do this one using generic approach.
:+1: 

> We could note the planned changes for setCustomVariables (maybe @deprecate ?)

They are not deprecated yet, maybe in 1-3 years. No need to add it yet but later for sure
