### ISSUE TITLE
Testserver for the exampe app

### ISSUE THREAD

**Issue by d4rken** [piwik/piwik-sdk-android#77]
@mattab Is it possible to get a test server/instance of piwik we can add as target for the example app?

I think the old one was supplied by @dotsbb and is no longer available.

**Comment by dotsbb** [comment]
@mattab Can we use http://demo.piwik.org/ for this purpose? Could You create a new site there?

**Comment by mattab** [comment]
Hi @d4rken @dotsbb - Sure, I've just sent you the credentials. Happy testing!

**Comment by mattab** [comment]
@dotsbb your CC email does not work anymore, can you please email me from your private email? i'll send you credentials
