### ISSUE TITLE
Setting connection timeout

### ISSUE THREAD

**Issue by indywidualny** [piwik/piwik-sdk-android#85]
I'm trying to change connection timeout from 5 to 10 seconds. My server is not very stable at the moment. I tried `mPiwikTracker.getDispatcher().setTimeOut(10000);` in try block below but `getDispatcher()` has protected access. My first question - why? And the second: how do it properly?

I post some code from the class extending Application class to make it easier. This is how I get the tracker.

```
public synchronized Tracker getTracker() {
        if (mPiwikTracker != null)
            return mPiwikTracker;

        try {
            mPiwikTracker = Piwik.getInstance(this).newTracker("http://indywidualni.org/analytics/piwik.php", 1);
            mPiwikTracker.setUserId(Settings.Secure.getString(getContentResolver(), Settings.Secure.ANDROID_ID));
            mPiwikTracker.setDispatchInterval(-1);
        } catch (MalformedURLException e) {
            Log.w("Piwik", "url is malformed", e);
            return null;
        }

        return mPiwikTracker;
    }
```

And a piece from onCreate

```
getTracker().trackAppDownload();
getTracker().dispatch();
```

**Comment by d4rken** [comment]
Hm yeah that is a problem.
The dispatcher is internal functionality, basically the ```Tracker``` is missing a setter for the timeout value.

I'll add a public method on the dev branch.

**Comment by d4rken** [comment]
The dev branch now contains setters. You can build a jar from the dev branch (see docs).
The next release will likely be when #83 is done.

**Comment by indywidualny** [comment]
`mPiwikTracker.setDispatchTimeout(30000);` works great. Thanks!

**Comment by dotsbb** [comment]
@indywidualny Maybe it's too late but anyway:
Have you seen this plugin https://github.com/piwik/plugin-QueuedTracking? I believe it can be useful for You.

**Comment by indywidualny** [comment]
Thanks. I'm just checking whether user is online. If there is network
connection I'm dispatching manually because I need only one information to
be sent. Just like I said, I'm counting app installations. The plugin is
not really necessary for me because it doesn't have to be 100% accurate. If
some data is missing that's ok. I need only most of it to know a little bit
about my users :)

pon., 8.02.2016 o 23:36 użytkownik Alexey Subbotin <notifications@github.com>
napisał:

**Comment by indywidualny** [comment]
Well. It's enough to just have a possibility to set timeout and I've already built a library from dev branch. The amount of data is not a problem for me. Just the timeout was the issue. Now everything is perfect. I'm dispatching manually just one thing so I wanted to make the timeout long enough to avoid missing stuff. I'm just counting app installations.
