### ISSUE TITLE
Cannot test it on a LocalHost

### ISSUE THREAD

**Issue by Shah-Sahab** [piwik/piwik-sdk-android#88]
Hi,

I am trying to test the sample application. Running wamp as a server on my system and using it as a local host. Already have installed piwik on wamp. Created a website: http://demo.piwik.com
And used it in my application class as:
 mPiwikTracker = getPiwik().newTracker("http://demo.piwik.com", 1);

Once application runs, I tap on different buttons in the demo app but the demo app doesnt record any clicks on against the local host.

**Comment by d4rken** [comment]
Check the configuration, by default the example app is in dryrun mode:
https://github.com/piwik/piwik-sdk-android/blob/master/exampleapp/src/main/java/com/piwik/demo/DemoApp.java#L37
